name: Gradle Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "8.0.312"
          architecture: x64
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build -iS
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build/libs

  generator:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Test the generator
        working-directory: generator
        run: npm test
